services:
  - type: web
    name: telegram-autopost-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: GROUP_ID
        sync: false
      - key: OWNER_ID
        sync: false

